"""org_id may be null

Revision ID: 5af0ee4e4b96
Revises: c1a9d9920232
Create Date: 2025-10-21 18:42:16.053379

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5af0ee4e4b96"
down_revision: str | Sequence[str] | None = "c1a9d9920232"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("activities_name_key"), "activities", type_="unique")
    op.create_unique_constraint(None, "organizations", ["name"])
    op.alter_column("phones", "organization_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("phones", "organization_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(None, "organizations", type_="unique")
    op.create_unique_constraint(
        op.f("activities_name_key"), "activities", ["name"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
