"""add is_active field for safety delete entity

Revision ID: c1a9d9920232
Revises: b36109f064f7
Create Date: 2025-10-20 20:54:05.225121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a9d9920232'
down_revision: Union[str, Sequence[str], None] = 'b36109f064f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('buildings', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('organizations', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('phones', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phones', 'is_active')
    op.drop_column('organizations', 'is_active')
    op.drop_column('buildings', 'is_active')
    op.drop_column('activities', 'is_active')
    # ### end Alembic commands ###
