services:
  organization_service:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "127.0.0.1:8001:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${POSTGRES_DB_URL}
      API_KEY: ${API_KEY}

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
