#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $POSTGRES_USER_NAME WITH PASSWORD '$POSTGRES_PASSWORD';
    CREATE DATABASE $POSTGRES_DB_NAME 
        OWNER $POSTGRES_USER_NAME 
        ENCODING 'UTF8' 
        LC_COLLATE 'ru_RU.UTF8' 
        LC_CTYPE 'ru_RU.UTF8' 
        TEMPLATE template0;
    
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB_NAME TO $POSTGRES_USER_NAME;
EOSQL